### ISSUE TITLE
Make a release (1.0.0)

### ISSUE THREAD

**Issue by dbacinski** [gtcompscientist/KelloCharts#2]
Can you create a version tag (1.0.0) in the repo, so that we can use exact version from JitPack: https://jitpack.io/#gtcompscientist/KelloCharts

**Comment by gtcompscientist** [comment]
I have tagged both releases in the repo for you. Apologies, I thought the script was tagging them already when I pushed to bintray.

**Comment by dbacinski** [comment]
Info what is a package and artifact name is missing in README.md, I wouldn't use JitPack if I would knew it was released:)
